# Web
server.port=8081

# H2
# Open Database Tool with following url while this app is running
#   localhost:<server.port><spring.h2.console.path>
#   localhost:8081/h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# Datasource
spring.datasource.url=jdbc:h2:file:~/qbot-h2-db
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update