# DISCORD
settings.discord.token=MTEyNTc5MzU5NjU0OTg5ODM0Mg.GqQsnt.9xErZ4mDkQKAjTkeUUdkNKBTNsFRNtn3X7btjA
settings.discord.invitelink=https://discord.com/api/oauth2/authorize?client_id=1125793596549898342&permissions=8&scope=bot
